import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { execFileSync } from 'child_process';
import {
  ensureThumbnail, thumbnailTextOf, thumbnailPath, thumbnailDir, GRAB_AT_SECONDS,
} from '../src/server/services/thumbnailService.js';

/**
 * The custom thumbnail: a frame from the render with the headline burned on.
 *
 * Run against a real 1-second video generated by ffmpeg rather than a mock, because
 * every property worth asserting — that a frame can be read at 1.5s, that the file is
 * reused until the render changes, that a missing headline still yields a thumbnail —
 * is a property of the files, and a mocked fs would prove none of them.
 */

const ffmpegPath = (await import('ffmpeg-static')).default as unknown as string;

let dir: string;
let video: string;
const ORIGINAL = { out: process.env.OUTPUTS_DIR, thumbs: process.env.THUMBNAIL_DIR };

/** A real, decodable mp4 long enough to seek into. testsrc is deterministic. */
const makeVideo = (file: string, seconds = 3) => {
  execFileSync(ffmpegPath, [
    '-hide_banner', '-loglevel', 'error',
    '-f', 'lavfi', '-i', `testsrc=size=360x640:rate=12:duration=${seconds}`,
    '-pix_fmt', 'yuv420p', '-y', file,
  ], { timeout: 60_000 });
};

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'thumb-'));
  process.env.OUTPUTS_DIR = dir;
  process.env.THUMBNAIL_DIR = path.join(dir, 'thumbnails');
  video = path.join(dir, 'render.mp4');
  makeVideo(video);
});

afterEach(() => {
  for (const [k, v] of [['OUTPUTS_DIR', ORIGINAL.out], ['THUMBNAIL_DIR', ORIGINAL.thumbs]] as const) {
    if (v === undefined) delete process.env[k]; else process.env[k] = v;
  }
  fs.rmSync(dir, { recursive: true, force: true });
});

describe('thumbnailTextOf', () => {
  it('reads the SEO agent’s headline under either field name', () => {
    expect(thumbnailTextOf({ seo_metadata: { thumbnailText: 'RAG: Truth for Your AI' } }))
      .toBe('RAG: Truth for Your AI');
    expect(thumbnailTextOf({ seoMetadata: { thumbnailText: '  Padded  ' } })).toBe('Padded');
  });

  it('is empty rather than undefined when there is no headline', () => {
    expect(thumbnailTextOf({})).toBe('');
    expect(thumbnailTextOf(null)).toBe('');
    expect(thumbnailTextOf({ seo_metadata: {} })).toBe('');
  });
});

describe('producing a thumbnail', () => {
  it('draws the headline onto a frame from the video', async () => {
    const res = await ensureThumbnail('p1', video, 'Tests FIX Themselves!');
    expect(res.hasText).toBe(true);
    expect(res.regenerated).toBe(true);
    expect(res.note).toBeUndefined();
    expect(res.path).toBe(thumbnailPath('p1'));
    expect(fs.statSync(res.path).size).toBeGreaterThan(1000);
    // Under YouTube's hard ceiling, which is a rejection rather than a warning.
    expect(fs.statSync(res.path).size).toBeLessThanOrEqual(2 * 1024 * 1024);
  }, 120_000);

  it('still produces a thumbnail when there is no headline to draw', async () => {
    // A plain frame is a perfectly good thumbnail. Refusing to make one would take the
    // download button down with it for every project the SEO agent has not run on.
    const res = await ensureThumbnail('p2', video, '');
    expect(fs.existsSync(res.path)).toBe(true);
    expect(res.hasText).toBe(false);
    expect(res.note).toMatch(/no thumbnailText/i);
  }, 120_000);

  it('refuses only when there is no video at all', async () => {
    await expect(ensureThumbnail('p3', path.join(dir, 'nope.mp4'), 'x'))
      .rejects.toThrow(/no rendered video/i);
    await expect(ensureThumbnail('p3', '', 'x')).rejects.toThrow(/no rendered video/i);
  });

  it('writes into the thumbnails directory, not next to the videos', async () => {
    await ensureThumbnail('p4', video, 'Hi');
    expect(fs.existsSync(path.join(thumbnailDir(), 'p4.jpg'))).toBe(true);
    expect(fs.existsSync(path.join(dir, 'p4.jpg'))).toBe(false);
  }, 120_000);
});

describe('when the work is reused', () => {
  it('does not rebuild an unchanged thumbnail', async () => {
    const first = await ensureThumbnail('p5', video, 'Same Words');
    const mtime = fs.statSync(first.path).mtimeMs;
    const second = await ensureThumbnail('p5', video, 'Same Words');
    expect(second.regenerated).toBe(false);
    expect(fs.statSync(second.path).mtimeMs).toBe(mtime);
  }, 120_000);

  it('rebuilds when the headline changes', async () => {
    await ensureThumbnail('p6', video, 'Before');
    const again = await ensureThumbnail('p6', video, 'After');
    expect(again.regenerated).toBe(true);
    expect(again.hasText).toBe(true);
  }, 120_000);

  it('rebuilds when the render is newer than the thumbnail', async () => {
    await ensureThumbnail('p7', video, 'Words');
    // A re-render rewrites the mp4. The thumbnail is now of the previous cut, which is
    // the stale-artifact bug isFreshOutput exists to catch everywhere else too.
    const later = Date.now() + 10_000;
    fs.utimesSync(video, later / 1000, later / 1000);
    expect((await ensureThumbnail('p7', video, 'Words')).regenerated).toBe(true);
  }, 120_000);
});

describe('the grab point', () => {
  it('is past the opening frame, so a fade-up is not the thumbnail', () => {
    expect(GRAB_AT_SECONDS).toBeGreaterThan(0.5);
    expect(GRAB_AT_SECONDS).toBeLessThan(3);
  });
});
